// pages/daily-ops/settings/eitje-api.vue
<template>
  <div class="container mx-auto py-8 px-4 max-w-4xl">
    <div class="mb-6">
      <h1 class="text-3xl font-bold tracking-tight">Eitje API Settings</h1>
      <p class="text-muted-foreground mt-2">
        Configure your Eitje API connection and automated sync schedules
      </p>
    </div>

    <div class="space-y-6">
      <UAlert
        v-if="connectionStatus !== 'idle' && activeTab === 'cron-jobs'"
        class="mb-2"
        :color="connectionStatus === 'success' ? 'green' : 'red'"
        :title="connectionStatus === 'success' ? 'Sync result' : 'Sync failed'"
        :description="connectionMessage"
        :icon="connectionStatus === 'success' ? 'i-lucide-check-circle' : 'i-lucide-x-circle'"
      />
      <div class="flex gap-2 border-b">
        <button
          :class="[
            'px-4 py-2 font-medium text-sm border-b-2 transition-colors',
            activeTab === 'credentials'
              ? 'border-gray-900 text-gray-900'
              : 'border-transparent text-gray-600 hover:text-gray-900'
          ]"
          @click="activeTab = 'credentials'"
        >
          Credentials
        </button>
        <button
          :class="[
            'px-4 py-2 font-medium text-sm border-b-2 transition-colors',
            activeTab === 'cron-jobs'
              ? 'border-gray-900 text-gray-900'
              : 'border-transparent text-gray-600 hover:text-gray-900'
          ]"
          @click="activeTab = 'cron-jobs'"
        >
          Cron Jobs
        </button>
      </div>

      <div v-if="activeTab === 'credentials'" class="space-y-6">
        <UCard>
          <template #header>
            <div class="space-y-1">
              <p class="font-semibold text-gray-900">API Credentials</p>
              <p class="text-sm text-gray-500">Enter your Eitje API credentials to connect to the platform</p>
            </div>
          </template>

          <div class="space-y-4">
            <div class="space-y-2">
              <label for="baseUrl" class="text-sm font-medium text-gray-700">Base URL</label>
              <UInput
                id="baseUrl"
                v-model="credentials.baseUrl"
                type="text"
                placeholder="https://open-api.eitje.app/open_api"
              />
            </div>

            <div class="space-y-2">
              <label for="partner_username" class="text-sm font-medium text-gray-700">Partner Username</label>
              <UInput
                id="partner_username"
                v-model="credentials.partner_username"
                type="text"
                placeholder="Your partner username"
              />
            </div>

            <div class="space-y-2">
              <label for="partner_password" class="text-sm font-medium text-gray-700">Partner Password</label>
              <UInput
                id="partner_password"
                v-model="credentials.partner_password"
                type="password"
                placeholder="Your partner password"
              />
            </div>

            <div class="space-y-2">
              <label for="api_username" class="text-sm font-medium text-gray-700">API Username</label>
              <UInput
                id="api_username"
                v-model="credentials.api_username"
                type="text"
                placeholder="Your API username"
              />
            </div>

            <div class="space-y-2">
              <label for="api_password" class="text-sm font-medium text-gray-700">API Password</label>
              <UInput
                id="api_password"
                v-model="credentials.api_password"
                type="password"
                placeholder="Your API password"
              />
            </div>

            <UAlert
              v-if="connectionStatus !== 'idle'"
              :color="connectionStatus === 'success' ? 'green' : 'red'"
              :title="connectionStatus === 'success' ? 'Connection successful!' : 'Connection failed'"
              :description="connectionMessage"
              :icon="connectionStatus === 'success' ? 'i-lucide-check-circle' : 'i-lucide-x-circle'"
            />

            <div class="flex gap-2">
              <UButton :loading="isSavingCredentials" @click="saveCredentials">
                <template #leading>
                  <UIcon name="i-lucide-save" />
                </template>
                Save Credentials
              </UButton>
              <UButton
                color="gray"
                variant="ghost"
                :loading="isTestingConnection"
                @click="testConnection"
              >
                <template #leading>
                  <UIcon name="i-lucide-test-tube" />
                </template>
                Test Connection
              </UButton>
            </div>
          </div>
        </UCard>
      </div>

      <div v-else-if="activeTab === 'cron-jobs'" class="space-y-6">
        <UCard>
          <template #header>
            <div class="space-y-1">
              <p class="font-semibold text-gray-900">Daily Data Sync</p>
              <p class="text-sm text-gray-500">Automated sync for daily labor and revenue data</p>
            </div>
          </template>

          <div class="space-y-4">
            <div class="flex items-center justify-between">
              <div class="space-y-0.5">
                <p class="text-sm font-medium text-gray-900">Enable Daily Data Sync</p>
                <p class="text-sm text-gray-600">Sync today's data at set times</p>
                <p class="text-xs text-gray-500">Sync runs at 01:00, 08:00, 15:00, 18:00, 19:00, 20:00, 21:00, 23:00 (Europe/Amsterdam)</p>
              </div>
              <USwitch
                :model-value="Boolean(dailyCronStatus?.isActive)"
                @update:model-value="(checked) => handleCronToggle('daily-data', checked)"
              />
            </div>

            <div class="border-t pt-4">
              <p class="text-sm font-semibold mb-2 block text-gray-900">Endpoints being synced:</p>
              <div class="grid grid-cols-2 gap-2 text-sm">
                <div class="flex items-center gap-2">
                  <UIcon name="i-lucide-check-circle" class="h-3 w-3 text-green-600" />
                  <span class="text-gray-600">time_registration_shifts</span>
                </div>
                <div class="flex items-center gap-2">
                  <UIcon name="i-lucide-check-circle" class="h-3 w-3 text-green-600" />
                  <span class="text-gray-600">revenue_days</span>
                </div>
                <div class="flex items-center gap-2">
                  <UIcon name="i-lucide-check-circle" class="h-3 w-3 text-green-600" />
                  <span class="text-gray-600">planning_shifts</span>
                </div>
                <div class="flex items-center gap-2">
                  <UIcon name="i-lucide-check-circle" class="h-3 w-3 text-green-600" />
                  <span class="text-gray-600">availability_shifts</span>
                </div>
                <div class="flex items-center gap-2">
                  <UIcon name="i-lucide-check-circle" class="h-3 w-3 text-green-600" />
                  <span class="text-gray-600">leave_requests</span>
                </div>
                <div class="flex items-center gap-2">
                  <UIcon name="i-lucide-check-circle" class="h-3 w-3 text-green-600" />
                  <span class="text-gray-600">events</span>
                </div>
              </div>
            </div>

            <p v-if="dailyCronStatus?.lastRun" class="text-sm text-gray-600">
              Last run: {{ new Date(String(dailyCronStatus.lastRunUTC || dailyCronStatus.lastRun)).toLocaleString() }}
            </p>
            <p v-if="dailyCronStatus?.lastSyncMessage" class="text-xs text-gray-500 mt-1">
              {{ dailyCronStatus.lastSyncOk ? 'Sync: ' : 'Last error: ' }}{{ dailyCronStatus.lastSyncMessage }}
            </p>
            <p v-if="!dailyCronStatus" class="text-sm text-gray-600">
              Cron job not configured yet. Toggle the switch to create it.
            </p>
            <UButton
              color="gray"
              variant="ghost"
              size="sm"
              :loading="runningNowJob === 'daily-data'"
              :disabled="!dailyCronStatus"
              @click="runNow('daily-data')"
            >
              Run Now
            </UButton>
          </div>
        </UCard>

        <UCard>
          <template #header>
            <div class="space-y-1">
              <p class="font-semibold text-gray-900">Master Data Sync</p>
              <p class="text-sm text-gray-500">Sync environments, teams, users, and shift types</p>
            </div>
          </template>

          <div class="space-y-4">
            <div class="flex items-center justify-between">
              <div class="space-y-0.5">
                <p class="text-sm font-medium text-gray-900">Enable Master Data Sync</p>
                <p class="text-sm text-gray-600">Sync master data daily</p>
              </div>
              <USwitch
                :model-value="Boolean(masterCronStatus?.isActive)"
                @update:model-value="(checked) => handleCronToggle('master-data', checked)"
              />
            </div>

            <div class="border-t pt-4">
              <p class="text-sm font-semibold mb-2 block text-gray-900">Endpoints being synced:</p>
              <div class="grid grid-cols-2 gap-2 text-sm">
                <div class="flex items-center gap-2">
                  <UIcon name="i-lucide-check-circle" class="h-3 w-3 text-green-600" />
                  <span class="text-gray-600">environments</span>
                </div>
                <div class="flex items-center gap-2">
                  <UIcon name="i-lucide-check-circle" class="h-3 w-3 text-green-600" />
                  <span class="text-gray-600">teams</span>
                </div>
                <div class="flex items-center gap-2">
                  <UIcon name="i-lucide-check-circle" class="h-3 w-3 text-green-600" />
                  <span class="text-gray-600">users</span>
                </div>
                <div class="flex items-center gap-2">
                  <UIcon name="i-lucide-check-circle" class="h-3 w-3 text-green-600" />
                  <span class="text-gray-600">shift_types</span>
                </div>
              </div>
            </div>

            <p v-if="masterCronStatus?.lastRun" class="text-sm text-gray-600">
              Last run: {{ new Date(String(masterCronStatus.lastRunUTC || masterCronStatus.lastRun)).toLocaleString() }}
            </p>
            <p v-if="masterCronStatus?.lastSyncMessage" class="text-xs text-gray-500 mt-1">
              {{ masterCronStatus.lastSyncOk ? 'Sync: ' : 'Last error: ' }}{{ masterCronStatus.lastSyncMessage }}
            </p>
            <p v-if="!masterCronStatus" class="text-sm text-gray-600">
              Cron job not configured yet. Toggle the switch to create it.
            </p>
            <UButton
              color="gray"
              variant="ghost"
              size="sm"
              :loading="runningNowJob === 'master-data'"
              :disabled="!masterCronStatus"
              @click="runNow('master-data')"
            >
              Run Now
            </UButton>
          </div>
        </UCard>

        <UCard>
          <template #header>
            <div class="space-y-1">
              <p class="font-semibold text-gray-900">Historical Data Sync</p>
              <p class="text-sm text-gray-500">Sync last 30 days of data to catch any missed changes</p>
            </div>
          </template>

          <div class="space-y-4">
            <div class="flex items-center justify-between">
              <div class="space-y-0.5">
                <p class="text-sm font-medium text-gray-900">Enable Historical Data Sync</p>
                <p class="text-sm text-gray-600">Sync last 30 days daily</p>
              </div>
              <USwitch
                :model-value="Boolean(historicalCronStatus?.isActive)"
                @update:model-value="(checked) => handleCronToggle('historical-data', checked)"
              />
            </div>

            <div class="border-t pt-4">
              <p class="text-sm font-semibold mb-2 block text-gray-900">Endpoints being synced:</p>
              <div class="grid grid-cols-2 gap-2 text-sm">
                <div class="flex items-center gap-2">
                  <UIcon name="i-lucide-check-circle" class="h-3 w-3 text-green-600" />
                  <span class="text-gray-600">time_registration_shifts</span>
                </div>
                <div class="flex items-center gap-2">
                  <UIcon name="i-lucide-check-circle" class="h-3 w-3 text-green-600" />
                  <span class="text-gray-600">revenue_days</span>
                </div>
                <div class="flex items-center gap-2">
                  <UIcon name="i-lucide-check-circle" class="h-3 w-3 text-green-600" />
                  <span class="text-gray-600">planning_shifts</span>
                </div>
                <div class="flex items-center gap-2">
                  <UIcon name="i-lucide-check-circle" class="h-3 w-3 text-green-600" />
                  <span class="text-gray-600">availability_shifts</span>
                </div>
                <div class="flex items-center gap-2">
                  <UIcon name="i-lucide-check-circle" class="h-3 w-3 text-green-600" />
                  <span class="text-gray-600">leave_requests</span>
                </div>
                <div class="flex items-center gap-2">
                  <UIcon name="i-lucide-check-circle" class="h-3 w-3 text-green-600" />
                  <span class="text-gray-600">events</span>
                </div>
              </div>
            </div>

            <p v-if="historicalCronStatus?.lastRun" class="text-sm text-gray-600">
              Last run: {{ new Date(String(historicalCronStatus.lastRunUTC || historicalCronStatus.lastRun)).toLocaleString() }}
            </p>
            <p v-if="historicalCronStatus?.lastSyncMessage" class="text-xs text-gray-500 mt-1">
              {{ historicalCronStatus.lastSyncOk ? 'Sync: ' : 'Last error: ' }}{{ historicalCronStatus.lastSyncMessage }}
            </p>
            <p v-if="!historicalCronStatus" class="text-sm text-gray-600">
              Cron job not configured yet. Toggle the switch to create it.
            </p>
            <UButton
              color="gray"
              variant="ghost"
              size="sm"
              :loading="runningNowJob === 'historical-data'"
              :disabled="!historicalCronStatus"
              @click="runNow('historical-data')"
            >
              Run Now
            </UButton>
          </div>
        </UCard>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, reactive } from 'vue'
import { useHead } from '#imports'

useHead({ title: 'Eitje API Settings' })

type EitjeSyncDetail = {
  ok?: boolean
  message?: string
  timeRegistration?: { upserted?: number; fetched?: number; error?: string }
  aggregation?: { inserted?: number; deletedPeriods?: number; error?: string }
  master?: { endpoints?: Array<{ name: string; fetched?: number; upserted?: number; error?: string }> }
}

type CronConfig = {
  isActive?: boolean
  lastRun?: string
  lastRunUTC?: string
  lastSyncAt?: string | null
  lastSyncOk?: boolean | null
  lastSyncMessage?: string | null
  lastSyncDetail?: EitjeSyncDetail | null
}

type CredentialsState = {
  baseUrl: string
  partner_username: string
  partner_password: string
  api_username: string
  api_password: string
}

const activeTab = ref<string>('credentials')

const credentials = reactive<CredentialsState>({
  baseUrl: 'https://open-api.eitje.app/open_api',
  partner_username: '',
  partner_password: '',
  api_username: '',
  api_password: '',
})

const isSavingCredentials = ref(false)
const isTestingConnection = ref(false)
const connectionStatus = ref<'idle' | 'success' | 'error'>('idle')
const connectionMessage = ref('')

const dailyCronStatus = ref<CronConfig | null>(null)
const masterCronStatus = ref<CronConfig | null>(null)
const historicalCronStatus = ref<CronConfig | null>(null)
const runningNowJob = ref<string | null>(null)

const loadCredentials = async () => {
  try {
    const response = await $fetch<{ success: boolean; credentials?: Record<string, unknown> }>('/api/eitje/v2/credentials')
    if (!response.success || !response.credentials) return

    const additionalConfig = (response.credentials.additionalConfig as Record<string, unknown> | undefined) ?? {}
    credentials.baseUrl = String(response.credentials.baseUrl ?? 'https://open-api.eitje.app/open_api')
    credentials.partner_username = String(additionalConfig.partner_username ?? '')
    credentials.partner_password = String(additionalConfig.partner_password ?? '')
    credentials.api_username = String(additionalConfig.api_username ?? '')
    credentials.api_password = String(additionalConfig.api_password ?? '')
  } catch (error) {
    console.error('Failed to load credentials:', error)
  }
}

const loadCronStatus = async () => {
  try {
    const [daily, master, historical] = await Promise.all([
      $fetch<{ success: boolean; data?: CronConfig }>('/api/eitje/v2/cron?jobType=daily-data'),
      $fetch<{ success: boolean; data?: CronConfig }>('/api/eitje/v2/cron?jobType=master-data'),
      $fetch<{ success: boolean; data?: CronConfig }>('/api/eitje/v2/cron?jobType=historical-data'),
    ])
    dailyCronStatus.value = daily.data ?? null
    masterCronStatus.value = master.data ?? null
    historicalCronStatus.value = historical.data ?? null
  } catch (error) {
    console.error('Failed to load cron status:', error)
  }
}

const saveCredentials = async () => {
  isSavingCredentials.value = true
  try {
    const response = await $fetch<{ success: boolean; error?: string }>('/api/eitje/v2/credentials', {
      method: 'POST',
      body: {
        baseUrl: credentials.baseUrl,
        additionalConfig: {
          partner_username: credentials.partner_username,
          partner_password: credentials.partner_password,
          api_username: credentials.api_username,
          api_password: credentials.api_password,
        },
      },
    })
    if (response.success) {
      connectionStatus.value = 'success'
      connectionMessage.value = 'Credentials saved successfully'
    } else {
      connectionStatus.value = 'error'
      connectionMessage.value = response.error || 'Failed to save credentials'
    }
  } catch (error: unknown) {
    connectionStatus.value = 'error'
    connectionMessage.value = error instanceof Error ? error.message : 'Failed to save credentials'
  } finally {
    isSavingCredentials.value = false
  }
}

const testConnection = async () => {
  isTestingConnection.value = true
  connectionStatus.value = 'idle'
  try {
    const response = await $fetch<{ success: boolean; message?: string; error?: string }>('/api/eitje/v2/sync', {
      method: 'POST',
      body: { endpoint: 'environments' },
    })
    if (response.success) {
      connectionStatus.value = 'success'
      connectionMessage.value = response.message || 'Connection successful!'
    } else {
      connectionStatus.value = 'error'
      connectionMessage.value = response.error || response.message || 'Connection failed'
    }
  } catch (error: unknown) {
    connectionStatus.value = 'error'
    connectionMessage.value = error instanceof Error ? error.message : 'Connection test failed'
  } finally {
    isTestingConnection.value = false
  }
}

const handleCronToggle = async (jobType: string, enabled: boolean) => {
  try {
    if (enabled) {
      const current = jobType === 'daily-data'
        ? dailyCronStatus.value
        : jobType === 'master-data'
          ? masterCronStatus.value
          : historicalCronStatus.value

      if (!current) {
        const defaultConfig = {
          isActive: true,
          schedule: jobType === 'daily-data' ? '0 1,8,15,18,19,20,21,23 * * *' :
                   jobType === 'master-data' ? '0 0 * * *' :
                   '0 1 * * *',
          enabledEndpoints: jobType === 'daily-data' || jobType === 'historical-data' ? {
            hours: true,
            revenue: true,
            planning: false,
          } : undefined,
          enabledMasterEndpoints: jobType === 'master-data' ? {
            environments: true,
            teams: true,
            users: true,
            shiftTypes: true,
          } : undefined,
        }

        await $fetch('/api/eitje/v2/cron', {
          method: 'POST',
          body: {
            action: 'update',
            jobType,
            config: defaultConfig,
          },
        })
      }
    }

    await $fetch('/api/eitje/v2/cron', {
      method: 'POST',
      body: {
        action: enabled ? 'start' : 'stop',
        jobType,
      },
    })

    await loadCronStatus()
  } catch (error: unknown) {
    connectionStatus.value = 'error'
    connectionMessage.value = error instanceof Error ? error.message : 'Action failed'
  }
}

const runNow = async (jobType: string) => {
  runningNowJob.value = jobType
  try {
    const response = await $fetch<{
      success: boolean
      message?: string
      sync?: EitjeSyncDetail & { jobType?: string; master?: EitjeSyncDetail['master'] }
    }>('/api/eitje/v2/cron', {
      method: 'POST',
      body: { action: 'run-now', jobType },
    })
    await loadCronStatus()
    connectionStatus.value = response.success ? 'success' : 'error'
    const detail = response.sync
    const parts: string[] = [response.message || (response.success ? 'Sync completed' : 'Sync failed')]
    if (detail?.timeRegistration) {
      parts.push(
        `Fetched ${detail.timeRegistration.fetched ?? 0}, upserted ${detail.timeRegistration.upserted ?? 0}`,
      )
    }
    if (detail?.aggregation) {
      parts.push(`Aggregation rows: ${detail.aggregation.inserted ?? 0}`)
    }
    if (detail?.master?.endpoints?.length) {
      parts.push(
        detail.master.endpoints.map((e) => `${e.name}: ${e.fetched ?? 0}`).join('; '),
      )
    }
    connectionMessage.value = parts.join(' · ')
  } catch (error: unknown) {
    connectionStatus.value = 'error'
    connectionMessage.value = error instanceof Error ? error.message : 'Run now failed'
  } finally {
    runningNowJob.value = null
  }
}

onMounted(async () => {
  await Promise.all([loadCredentials(), loadCronStatus()])
})
</script>

// app/(authenticated)/settings/eitje-api/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Checkbox } from '@/components/ui/checkbox'
import { Loader2, Save, TestTube, CheckCircle, XCircle, Settings } from 'lucide-react'
import { toast } from 'sonner'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { useEnvironment } from '@/lib/environmentContext'

export default function EitjeApiSettingsPage() {
  const { activeEnvironment, setActiveEnvironment } = useEnvironment()

  // Ensure we're in Daily Ops environment when this page loads
  useEffect(() => {
    if (activeEnvironment !== 'daily-ops') {
      setActiveEnvironment('daily-ops')
    }
  }, [activeEnvironment, setActiveEnvironment])
  const [credentials, setCredentials] = useState({
    baseUrl: 'https://open-api.eitje.app/open_api',
    partner_username: '',
    partner_password: '',
    api_username: '',
    api_password: '',
  })
  const [isLoading, setIsLoading] = useState(false)
  const [isTesting, setIsTesting] = useState(false)
  const [connectionStatus, setConnectionStatus] = useState<'idle' | 'success' | 'error'>('idle')
  const [connectionMessage, setConnectionMessage] = useState('')

  // Cron job states
  const [dailyCronStatus, setDailyCronStatus] = useState<any>(null)
  const [masterCronStatus, setMasterCronStatus] = useState<any>(null)
  const [historicalCronStatus, setHistoricalCronStatus] = useState<any>(null)
  const [isLoadingCronStatus, setIsLoadingCronStatus] = useState(false)

  // Load existing credentials
  useEffect(() => {
    const loadCredentials = async () => {
      try {
        const response = await fetch('/api/eitje/v2/credentials')
        if (response.ok) {
          const data = await response.json()
          if (data.success && data.credentials) {
            setCredentials({
              baseUrl: data.credentials.baseUrl || 'https://open-api.eitje.app/open_api',
              partner_username: data.credentials.additionalConfig?.partner_username || '',
              partner_password: data.credentials.additionalConfig?.partner_password || '',
              api_username: data.credentials.additionalConfig?.api_username || '',
              api_password: data.credentials.additionalConfig?.api_password || '',
            })
          }
        }
      } catch (error) {
        console.error('Error loading credentials:', error)
      }
    }
    loadCredentials()
    loadCronStatus()
  }, [])

  const loadCronStatus = async () => {
    setIsLoadingCronStatus(true)
    try {
      const [daily, master, historical] = await Promise.all([
        fetch('/api/eitje/v2/cron?jobType=daily-data'),
        fetch('/api/eitje/v2/cron?jobType=master-data'),
        fetch('/api/eitje/v2/cron?jobType=historical-data'),
      ])

      if (daily.ok) {
        const data = await daily.json()
        if (data.success) setDailyCronStatus(data.data)
      }
      if (master.ok) {
        const data = await master.json()
        if (data.success) setMasterCronStatus(data.data)
      }
      if (historical.ok) {
        const data = await historical.json()
        if (data.success) setHistoricalCronStatus(data.data)
      }
    } catch (error) {
      console.error('Error loading cron status:', error)
    } finally {
      setIsLoadingCronStatus(false)
    }
  }

  const handleSaveCredentials = async () => {
    setIsLoading(true)
    try {
      const response = await fetch('/api/eitje/v2/credentials', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          baseUrl: credentials.baseUrl,
          additionalConfig: {
            partner_username: credentials.partner_username,
            partner_password: credentials.partner_password,
            api_username: credentials.api_username,
            api_password: credentials.api_password,
          },
        }),
      })

      const result = await response.json()
      if (result.success) {
        toast.success('Credentials saved successfully')
      } else {
        toast.error(result.error || 'Failed to save credentials')
      }
    } catch (error: any) {
      toast.error(error.message || 'Failed to save credentials')
    } finally {
      setIsLoading(false)
    }
  }

  const handleTestConnection = async () => {
    setIsTesting(true)
    setConnectionStatus('idle')
    try {
      const response = await fetch('/api/eitje/v2/sync', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          endpoint: 'environments',
        }),
      })

      const result = await response.json()
      if (result.success) {
        setConnectionStatus('success')
        setConnectionMessage('Connection successful!')
        toast.success('Connection test successful')
      } else {
        setConnectionStatus('error')
        setConnectionMessage(result.error || 'Connection failed')
        toast.error(result.error || 'Connection test failed')
      }
    } catch (error: any) {
      setConnectionStatus('error')
      setConnectionMessage(error.message || 'Connection test failed')
      toast.error(error.message || 'Connection test failed')
    } finally {
      setIsTesting(false)
    }
  }

  const handleCronAction = async (jobType: string, action: string, config?: any) => {
    try {
      // If trying to start a job that doesn't exist, create it first with default config
      if (action === 'start') {
        const currentStatus = 
          jobType === 'daily-data' ? dailyCronStatus :
          jobType === 'master-data' ? masterCronStatus :
          historicalCronStatus
        
        if (!currentStatus) {
          // Create the job with default configuration
          const defaultConfig = {
            isActive: true,
            schedule: jobType === 'daily-data' ? '0 * * * *' : // Hourly
                     jobType === 'master-data' ? '0 0 * * *' : // Daily at midnight
                     '0 1 * * *', // Daily at 1 AM for historical
            enabledEndpoints: jobType === 'daily-data' || jobType === 'historical-data' ? {
              hours: true,
              revenue: true,
              planning: false,
            } : undefined,
            enabledMasterEndpoints: jobType === 'master-data' ? {
              environments: true,
              teams: true,
              users: true,
              shiftTypes: true,
            } : undefined,
          }
          
          const createResponse = await fetch('/api/eitje/v2/cron', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              action: 'update',
              jobType,
              config: defaultConfig,
            }),
          })
          
          const createResult = await createResponse.json()
          if (!createResult.success) {
            toast.error(createResult.error || 'Failed to create cron job')
            return
          }
        }
      }
      
      const response = await fetch('/api/eitje/v2/cron', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action,
          jobType,
          config,
        }),
      })

      const result = await response.json()
      if (result.success) {
        toast.success(result.message || 'Action completed successfully')
        await loadCronStatus()
      } else {
        toast.error(result.error || 'Action failed')
      }
    } catch (error: any) {
      console.error('Cron action error:', error)
      toast.error(error.message || 'Action failed')
    }
  }

  return (
    <div className="container mx-auto py-8 px-4 max-w-4xl">
      <div className="mb-6">
        <h1 className="text-3xl font-bold tracking-tight">Eitje API Settings</h1>
        <p className="text-muted-foreground mt-2">
          Configure your Eitje API connection and automated sync schedules
        </p>
      </div>

      <Tabs defaultValue="credentials" className="space-y-6">
        <TabsList>
          <TabsTrigger value="credentials">Credentials</TabsTrigger>
          <TabsTrigger value="cron-jobs">Cron Jobs</TabsTrigger>
        </TabsList>

        <TabsContent value="credentials" className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>API Credentials</CardTitle>
              <CardDescription>
                Enter your Eitje API credentials to connect to the platform
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="baseUrl">Base URL</Label>
                <Input
                  id="baseUrl"
                  value={credentials.baseUrl}
                  onChange={(e) => setCredentials({ ...credentials, baseUrl: e.target.value })}
                  placeholder="https://open-api.eitje.app/open_api"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="partner_username">Partner Username</Label>
                <Input
                  id="partner_username"
                  type="text"
                  value={credentials.partner_username}
                  onChange={(e) => setCredentials({ ...credentials, partner_username: e.target.value })}
                  placeholder="Your partner username"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="partner_password">Partner Password</Label>
                <Input
                  id="partner_password"
                  type="password"
                  value={credentials.partner_password}
                  onChange={(e) => setCredentials({ ...credentials, partner_password: e.target.value })}
                  placeholder="Your partner password"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="api_username">API Username</Label>
                <Input
                  id="api_username"
                  type="text"
                  value={credentials.api_username}
                  onChange={(e) => setCredentials({ ...credentials, api_username: e.target.value })}
                  placeholder="Your API username"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="api_password">API Password</Label>
                <Input
                  id="api_password"
                  type="password"
                  value={credentials.api_password}
                  onChange={(e) => setCredentials({ ...credentials, api_password: e.target.value })}
                  placeholder="Your API password"
                />
              </div>

              {connectionStatus !== 'idle' && (
                <Alert variant={connectionStatus === 'success' ? 'default' : 'destructive'}>
                  <AlertDescription className="flex items-center gap-2">
                    {connectionStatus === 'success' ? (
                      <CheckCircle className="h-4 w-4" />
                    ) : (
                      <XCircle className="h-4 w-4" />
                    )}
                    {connectionMessage}
                  </AlertDescription>
                </Alert>
              )}

              <div className="flex gap-2">
                <Button onClick={handleSaveCredentials} disabled={isLoading}>
                  {isLoading ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Saving...
                    </>
                  ) : (
                    <>
                      <Save className="mr-2 h-4 w-4" />
                      Save Credentials
                    </>
                  )}
                </Button>
                <Button variant="outline" onClick={handleTestConnection} disabled={isTesting}>
                  {isTesting ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Testing...
                    </>
                  ) : (
                    <>
                      <TestTube className="mr-2 h-4 w-4" />
                      Test Connection
                    </>
                  )}
                </Button>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="cron-jobs" className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Daily Data Sync</CardTitle>
              <CardDescription>Automated sync for daily labor and revenue data</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <div className="space-y-0.5">
                  <Label>Enable Daily Data Sync</Label>
                  <p className="text-sm text-muted-foreground">
                    Sync today&apos;s data hourly
                  </p>
                </div>
                <Switch
                  checked={dailyCronStatus?.isActive || false}
                  onCheckedChange={(checked) =>
                    handleCronAction('daily-data', checked ? 'start' : 'stop')
                  }
                />
              </div>
              
              <div className="border-t pt-4">
                <Label className="text-sm font-semibold mb-2 block">Endpoints being synced:</Label>
                <div className="grid grid-cols-2 gap-2 text-sm">
                  <div className="flex items-center gap-2">
                    <CheckCircle className="h-3 w-3 text-green-600" />
                    <span className="text-muted-foreground">time_registration_shifts</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <CheckCircle className="h-3 w-3 text-green-600" />
                    <span className="text-muted-foreground">revenue_days</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <CheckCircle className="h-3 w-3 text-green-600" />
                    <span className="text-muted-foreground">planning_shifts</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <CheckCircle className="h-3 w-3 text-green-600" />
                    <span className="text-muted-foreground">availability_shifts</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <CheckCircle className="h-3 w-3 text-green-600" />
                    <span className="text-muted-foreground">leave_requests</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <CheckCircle className="h-3 w-3 text-green-600" />
                    <span className="text-muted-foreground">events</span>
                  </div>
                </div>
              </div>

              {dailyCronStatus?.lastRun && (
                <p className="text-sm text-muted-foreground">
                  Last run: {new Date(dailyCronStatus.lastRunUTC || dailyCronStatus.lastRun).toLocaleString()}
                </p>
              )}
              {!dailyCronStatus && (
                <p className="text-sm text-muted-foreground">
                  Cron job not configured yet. Toggle the switch to create it.
                </p>
              )}
              <Button
                variant="outline"
                size="sm"
                onClick={() => handleCronAction('daily-data', 'run-now')}
                disabled={!dailyCronStatus}
              >
                Run Now
              </Button>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Master Data Sync</CardTitle>
              <CardDescription>Sync environments, teams, users, and shift types</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <div className="space-y-0.5">
                  <Label>Enable Master Data Sync</Label>
                  <p className="text-sm text-muted-foreground">
                    Sync master data daily
                  </p>
                </div>
                <Switch
                  checked={masterCronStatus?.isActive || false}
                  onCheckedChange={(checked) =>
                    handleCronAction('master-data', checked ? 'start' : 'stop')
                  }
                />
              </div>
              
              <div className="border-t pt-4">
                <Label className="text-sm font-semibold mb-2 block">Endpoints being synced:</Label>
                <div className="grid grid-cols-2 gap-2 text-sm">
                  <div className="flex items-center gap-2">
                    <CheckCircle className="h-3 w-3 text-green-600" />
                    <span className="text-muted-foreground">environments</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <CheckCircle className="h-3 w-3 text-green-600" />
                    <span className="text-muted-foreground">teams</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <CheckCircle className="h-3 w-3 text-green-600" />
                    <span className="text-muted-foreground">users</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <CheckCircle className="h-3 w-3 text-green-600" />
                    <span className="text-muted-foreground">shift_types</span>
                  </div>
                </div>
              </div>

              {masterCronStatus?.lastRun && (
                <p className="text-sm text-muted-foreground">
                  Last run: {new Date(masterCronStatus.lastRunUTC || masterCronStatus.lastRun).toLocaleString()}
                </p>
              )}
              {!masterCronStatus && (
                <p className="text-sm text-muted-foreground">
                  Cron job not configured yet. Toggle the switch to create it.
                </p>
              )}
              <Button
                variant="outline"
                size="sm"
                onClick={() => handleCronAction('master-data', 'run-now')}
                disabled={!masterCronStatus}
              >
                Run Now
              </Button>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Historical Data Sync</CardTitle>
              <CardDescription>Sync last 30 days of data to catch any missed changes</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-center justify-between">
                <div className="space-y-0.5">
                  <Label>Enable Historical Data Sync</Label>
                  <p className="text-sm text-muted-foreground">
                    Sync last 30 days daily
                  </p>
                </div>
                <Switch
                  checked={historicalCronStatus?.isActive || false}
                  onCheckedChange={(checked) =>
                    handleCronAction('historical-data', checked ? 'start' : 'stop')
                  }
                />
              </div>
              
              <div className="border-t pt-4">
                <Label className="text-sm font-semibold mb-2 block">Endpoints being synced:</Label>
                <div className="grid grid-cols-2 gap-2 text-sm">
                  <div className="flex items-center gap-2">
                    <CheckCircle className="h-3 w-3 text-green-600" />
                    <span className="text-muted-foreground">time_registration_shifts</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <CheckCircle className="h-3 w-3 text-green-600" />
                    <span className="text-muted-foreground">revenue_days</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <CheckCircle className="h-3 w-3 text-green-600" />
                    <span className="text-muted-foreground">planning_shifts</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <CheckCircle className="h-3 w-3 text-green-600" />
                    <span className="text-muted-foreground">availability_shifts</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <CheckCircle className="h-3 w-3 text-green-600" />
                    <span className="text-muted-foreground">leave_requests</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <CheckCircle className="h-3 w-3 text-green-600" />
                    <span className="text-muted-foreground">events</span>
                  </div>
                </div>
              </div>

              {historicalCronStatus?.lastRun && (
                <p className="text-sm text-muted-foreground">
                  Last run: {new Date(historicalCronStatus.lastRunUTC || historicalCronStatus.lastRun).toLocaleString()}
                </p>
              )}
              {!historicalCronStatus && (
                <p className="text-sm text-muted-foreground">
                  Cron job not configured yet. Toggle the switch to create it.
                </p>
              )}
              <Button
                variant="outline"
                size="sm"
                onClick={() => handleCronAction('historical-data', 'run-now')}
                disabled={!historicalCronStatus}
              >
                Run Now
              </Button>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  )
}
