// pages/daily-ops/hours.vue
<template>
  <div class="space-y-6">
    <div>
      <h1 class="text-3xl font-bold text-gray-900">Hours Overview</h1>
      <p class="text-gray-500">View hours worked per day per location</p>
    </div>

    <UCard v-if="error" class="border-red-200">
      <p class="text-red-600"><strong>Error:</strong> {{ error }}</p>
    </UCard>

    <UCard>
      <template #header>
        <h2 class="font-semibold">Filters</h2>
        <p class="text-sm text-gray-500">Filter and sort hours data</p>
      </template>
      <DailyOpsDateLocationFilter
        :model-value="{ locationId: filters.locationId, startDate: filters.startDate, endDate: filters.endDate }"
        :locations="locations"
        @update:model-value="(updates) => { Object.assign(filters, updates); fetchHours(true) }"
      />
      <div class="mt-6 grid gap-4 md:grid-cols-3">
        <div class="space-y-2">
          <label class="text-sm font-medium">Endpoint</label>
          <USelectMenu
            v-model="filters.endpoint"
            :items="endpointOptions"
            value-attribute="value"
            class="w-full"
            @update:model-value="() => fetchHours(true)"
          />
        </div>
        <div class="space-y-2">
          <label class="text-sm font-medium">Sort By</label>
          <USelectMenu
            v-model="filters.sortBy"
            :items="sortByOptions"
            value-attribute="value"
            class="w-full"
            @update:model-value="() => fetchHours(true)"
          />
        </div>
        <div class="space-y-2">
          <label class="text-sm font-medium">Order</label>
          <USelectMenu
            v-model="filters.sortOrder"
            :items="[{ label: 'Descending', value: 'desc' }, { label: 'Ascending', value: 'asc' }]"
            value-attribute="value"
            class="w-full"
            @update:model-value="() => fetchHours(true)"
          />
        </div>
      </div>
      <div class="mt-6 flex flex-wrap gap-2">
        <UButton variant="outline" @click="resetFilters">Reset Filters</UButton>
        <UButton :loading="loading" @click="() => fetchHours(true)">Refresh data</UButton>
      </div>
    </UCard>

    <div v-if="paginationTotal > 0" class="grid gap-4 md:grid-cols-3">
      <UCard>
        <template #header>
          <span class="text-sm font-medium">Total Hours</span>
        </template>
        <p class="text-2xl font-bold">{{ totalHours.toFixed(2) }}h</p>
      </UCard>
      <UCard>
        <template #header>
          <span class="text-sm font-medium">Total Cost</span>
        </template>
        <p class="text-2xl font-bold">€{{ totalCost.toFixed(2) }}</p>
      </UCard>
      <UCard>
        <template #header>
          <span class="text-sm font-medium">Total Records</span>
        </template>
        <p class="text-2xl font-bold">{{ totalRecords }}</p>
      </UCard>
    </div>

    <UCard>
      <template #header>
        <h2 class="font-semibold">Hours by Day and Location</h2>
        <p class="text-sm text-gray-500">
          {{ loading ? 'Loading...' : `${paginationTotal} record(s) total · ${hoursData.length} on this page` }}
        </p>
        <p v-if="!loading" class="text-xs text-gray-500">
          Rows are grouped by each shift's work day (Europe/Amsterdam), not by when sync ran. Use Refresh after a sync if this tab was already open.
        </p>
      </template>
      <div v-if="loading" class="py-8 text-center text-gray-500">Loading hours data...</div>
      <template v-else>
        <div class="overflow-x-auto">
          <table class="w-full text-left text-sm">
            <thead>
              <tr class="border-b">
                <th class="pb-2 pr-4 font-medium">Date</th>
                <th class="pb-2 pr-4 font-medium">Location</th>
                <th class="pb-2 pr-4 font-medium">Total Hours</th>
                <th class="pb-2 pr-4 font-medium">Total Cost</th>
                <th class="pb-2 pr-4 font-medium">Records</th>
                <th class="w-10 pb-2 pl-2 text-right font-medium" />
              </tr>
            </thead>
            <tbody>
              <!-- eslint-disable-next-line vue/no-v-for-template-key -- Vue 3 requires key on <template> when it has multiple root elements -->
              <template v-for="(row, i) in hoursData" :key="i">
                <tr
                  class="border-b cursor-pointer transition-colors hover:bg-gray-50"
                  :class="{ 'bg-gray-50': expandedRow === i }"
                  @click="expandedRow = expandedRow === i ? null : i"
                >
                  <td class="py-2 pr-4">{{ formatDate(row.date) }}</td>
                  <td class="py-2 pr-4">{{ row.location_name || 'Unknown' }}</td>
                  <td class="py-2 pr-4">{{ row.total_hours != null ? Number(row.total_hours).toFixed(2) : '-' }}</td>
                  <td class="py-2 pr-4">€{{ row.total_cost != null ? Number(row.total_cost).toFixed(2) : '0.00' }}</td>
                  <td class="py-2 pr-4">{{ row.record_count ?? 0 }}</td>
                  <td class="py-2 pl-2 text-right">
                    <UIcon
                      name="i-lucide-chevron-down"
                      :class="['size-4 inline-block transition-transform', expandedRow === i && 'rotate-180']"
                    />
                  </td>
                </tr>
                <tr v-if="expandedRow === i" class="border-b bg-gray-50/80">
                  <td colspan="6" class="p-4">
                    <div class="rounded-lg border border-gray-200 bg-white p-4 shadow-sm">
                      <h5 class="mb-2 text-xs font-semibold uppercase tracking-wide text-gray-500">Breakdown by worker & team</h5>
                      <p class="mb-2 text-xs text-gray-500">Shows aggregated hours per worker per team for this date and location.</p>
                      <div v-if="rowDetailLoading" class="py-4 text-center text-sm text-gray-500">Loading...</div>
                      <div v-else-if="rowDetailError" class="py-2 text-sm text-red-600">{{ rowDetailError }}</div>
                      <div v-else class="overflow-x-auto">
                        <table class="w-full text-left text-sm">
                          <thead>
                            <tr class="border-b text-gray-500">
                              <th class="w-10 pb-2 pr-4 font-medium">#</th>
                              <th class="pb-2 pr-4 font-medium">Worker</th>
                              <th class="pb-2 pr-4 font-medium">Team</th>
                              <th class="pb-2 pr-4 text-right font-medium">Hours</th>
                              <th class="pb-2 pr-4 text-right font-medium">Cost</th>
                              <th class="pb-2 text-right font-medium">Shifts</th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr v-for="(rec, j) in rowDetailRecords" :key="j" class="border-b last:border-0">
                              <td class="py-1.5 pr-4 text-gray-500">{{ j + 1 }}</td>
                              <td class="py-1.5 pr-4">{{ rec.worker_name }}</td>
                              <td class="py-1.5 pr-4">{{ rec.team_name }}</td>
                              <td class="py-1.5 pr-4 text-right font-mono">{{ Number(rec.total_hours).toFixed(2) }}</td>
                              <td class="py-1.5 pr-4 text-right font-mono">€{{ Number(rec.total_cost).toFixed(2) }}</td>
                              <td class="py-1.5 text-right font-mono text-xs text-gray-600">{{ rec.record_count }}</td>
                            </tr>
                          </tbody>
                          <tfoot v-if="rowDetailRecords.length > 0">
                            <tr class="border-t-2 font-medium">
                              <td class="py-2 pr-4" colspan="3">Sum of above</td>
                              <td class="py-2 text-right font-mono">{{ rowDetailSumHours.toFixed(2) }}</td>
                              <td class="py-2 text-right font-mono">€{{ rowDetailSumCost.toFixed(2) }}</td>
                              <td class="py-2 text-right font-mono text-xs" />
                            </tr>
                            <tr class="text-gray-600">
                              <td class="py-1 pr-4 text-xs" colspan="3">Row total (from aggregation)</td>
                              <td class="py-1 text-right text-xs font-mono">{{ row.total_hours != null ? Number(row.total_hours).toFixed(2) : '-' }}</td>
                              <td class="py-1 text-right text-xs font-mono">€{{ row.total_cost != null ? Number(row.total_cost).toFixed(2) : '-' }}</td>
                              <td class="py-1 text-right text-xs" />
                            </tr>
                          </tfoot>
                        </table>
                        <p v-if="rowDetailRecords.length > 0 && Math.abs(rowDetailSumHours - Number(row.total_hours ?? 0)) > 0.02" class="mt-2 rounded bg-amber-50 p-2 text-sm text-amber-800">
                          <strong>Mismatch:</strong> sum of raw ({{ rowDetailSumHours.toFixed(2) }}) ≠ row total ({{ row.total_hours != null ? Number(row.total_hours).toFixed(2) : '-' }}). See “Check consistency” below for causes.
                        </p>
                        <p v-if="rowDetailRecords.length > 0 && Math.abs(rowDetailSumHours - Number(row.total_hours ?? 0)) > 0.02" class="mt-2 rounded bg-amber-50 p-2 text-sm text-amber-800">
                          <strong>Mismatch:</strong> sum of worker/team rows ({{ rowDetailSumHours.toFixed(2) }}) ≠ day total ({{ row.total_hours != null ? Number(row.total_hours).toFixed(2) : '-' }}). This should not happen—check data consistency.
                        </p>
                      </div>
                    </div>
                  </td>
                </tr>
              </template>
            </tbody>
          </table>
        </div>
        <div v-if="paginationTotal > pageSize" class="mt-6 flex justify-center">
          <UPagination :page="page" :total="paginationTotal" :items-per-page="pageSize" @update:page="onPageChange" />
        </div>
        <p v-if="hoursData.length === 0 && !loading" class="mt-4 text-center text-sm text-gray-500">
          Hours data is synced from the Eitje API. Configure Settings → Eitje API and run sync to populate.
        </p>
        <div class="mt-4 border-t pt-4">
          <UButton variant="outline" size="sm" :loading="consistencyLoading" @click="runConsistencyCheck">
            Check consistency (aggregation vs raw sums)
          </UButton>
          <div v-if="consistencyResult" class="mt-3 rounded-lg border border-gray-200 bg-gray-50 p-3 text-sm">
            <p class="font-medium">
              {{ consistencyResult.summary.mismatch_count }} mismatch(es) of {{ consistencyResult.summary.total_rows }} rows.
            </p>
            <table v-if="consistencyResult.mismatches.length" class="mt-2 w-full text-left text-xs">
              <thead>
                <tr class="border-b text-gray-500">
                  <th class="pb-1 pr-2">Date</th>
                  <th class="pb-1 pr-2">Location</th>
                  <th class="pb-1 pr-2 text-right">Row total</th>
                  <th class="pb-1 pr-2 text-right">Raw sum</th>
                  <th class="pb-1 pr-2 text-right">Diff</th>
                  <th class="pb-1">Raw #</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="(m, i) in consistencyResult.mismatches" :key="i" class="border-b">
                  <td class="py-1 pr-2">{{ m.date }}</td>
                  <td class="py-1 pr-2">{{ m.location_name }}</td>
                  <td class="py-1 pr-2 text-right font-mono">{{ m.row_total.toFixed(2) }}</td>
                  <td class="py-1 pr-2 text-right font-mono">{{ m.raw_sum.toFixed(2) }}</td>
                  <td class="py-1 pr-2 text-right font-mono text-amber-600">{{ m.diff.toFixed(2) }}</td>
                  <td class="py-1">{{ m.raw_count }} vs {{ m.row_record_count }}</td>
                </tr>
              </tbody>
            </table>
            <p class="mt-3 text-gray-600">{{ consistencyResult.possible_causes }}</p>
          </div>
        </div>
      </template>
    </UCard>
  </div>
</template>

<script setup lang="ts">
/**
 * @registry-id: dailyOpsHoursPage
 * @last-modified: 2026-07-02T00:00:00.000Z
 * @description: Hours overview — direct DB reads
 * @last-fix: [2026-07-02] ADR-013 read-cache metadata
 * @adr-ref: ADR-013
 * @data-source: direct-db
 * @read-cache-json: none
 * @imports-data-from: GET /api/hours/*
 */
const endpointOptions = [
  { label: 'Time Registration Shifts', value: 'time_registration_shifts' },
  { label: 'Revenue Days', value: 'revenue_days' },
  { label: 'Planning Shifts', value: 'planning_shifts' },
]
const sortByOptions = [
  { label: 'Date', value: 'date' },
  { label: 'Location', value: 'location_name' },
  { label: 'Total Hours', value: 'total_hours' },
]

const { startDate: defaultStart, endDate: defaultEnd } = getLast30DaysRange()

const filters = reactive({
  startDate: defaultStart,
  endDate: defaultEnd,
  locationId: 'all',
  endpoint: 'time_registration_shifts',
  sortBy: 'date',
  sortOrder: 'desc',
})

const hoursData = ref<Record<string, unknown>[]>([])
const locations = ref<{ _id: string; name: string }[]>([])
const loading = ref(true)
const error = ref<string | null>(null)
const page = ref(1)
const pageSize = 50
const paginationTotal = ref(0)
const rangeTotals = ref({ total_hours: 0, total_cost: 0, record_count: 0 })
const expandedRow = ref<number | null>(null)
const rowDetailRecords = ref<{ worker_name: string; team_name: string; total_hours: number; total_cost: number; record_count: number }[]>([])
const rowDetailLoading = ref(false)
const rowDetailError = ref<string | null>(null)
const consistencyLoading = ref(false)
const consistencyResult = ref<{
  summary: { total_rows: number; ok_count: number; mismatch_count: number }
  mismatches: { date: string; location_name: string; location_id: string; row_total: number; raw_sum: number; raw_count: number; row_record_count: number; diff: number }[]
  possible_causes: string
} | null>(null)

const totalHours = computed(() => rangeTotals.value.total_hours)
const rowDetailSumHours = computed(() => rowDetailRecords.value.reduce((s: number, r: { total_hours: number }) => s + Number(r.total_hours ?? 0), 0))
const rowDetailSumCost = computed(() => rowDetailRecords.value.reduce((s: number, r: { total_cost: number }) => s + Number(r.total_cost ?? 0), 0))
const totalCost = computed(() => rangeTotals.value.total_cost)
const totalRecords = computed(() => Math.round(rangeTotals.value.record_count))

function formatDate (d: unknown) {
  if (!d) return '-'
  const date = new Date(String(d))
  return date.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })
}

async function fetchRowDetail (row: Record<string, unknown>) {
  rowDetailLoading.value = true
  rowDetailError.value = null
  rowDetailRecords.value = []
  try {
    const dateVal = row.date
    const dateStr = dateVal instanceof Date ? dateVal.toISOString().split('T')[0] : String(dateVal ?? '').slice(0, 10)
    const locId = row.location_id != null ? String(row.location_id) : ''
    const locName = row.location_name != null ? String(row.location_name).trim() : ''
    const params = new URLSearchParams()
    params.set('date', dateStr || '')
    if (locName) params.set('locationName', locName)
    if (locId && /^[a-f0-9]{24}$/i.test(locId)) {
      params.set('locationId', locId)
    }
    params.set('endpoint', filters.endpoint || 'time_registration_shifts')
    const res = await $fetch<{ success: boolean; data?: { worker_name: string; team_name: string; total_hours: number; total_cost: number; record_count: number }[] }>(`/api/hours-row-detail?${params}`)
    rowDetailRecords.value = res.success ? (res.data ?? []) : []
  } catch (e: unknown) {
    rowDetailError.value = e instanceof Error ? e.message : 'Failed to load records'
  } finally {
    rowDetailLoading.value = false
  }
}

watch(expandedRow, (idx: number | null) => {
  if (idx === null) {
    rowDetailRecords.value = []
    rowDetailError.value = null
    return
  }
  const row = hoursData.value[idx]
  if (row) fetchRowDetail(row)
})

async function fetchHours (resetPage = false) {
  if (resetPage) page.value = 1
  loading.value = true
  error.value = null
  expandedRow.value = null
  try {
    const params = new URLSearchParams()
    if (filters.startDate) params.set('startDate', filters.startDate)
    if (filters.endDate) params.set('endDate', filters.endDate)
    if (filters.locationId && filters.locationId !== 'all') params.set('locationId', filters.locationId)
    params.set('endpoint', filters.endpoint)
    params.set('groupBy', 'date_location')
    params.set('sortBy', filters.sortBy)
    params.set('sortOrder', filters.sortOrder)
    params.set('page', String(page.value))
    params.set('pageSize', String(pageSize))
    const res = await $fetch<{
      success: boolean
      data?: Record<string, unknown>[]
      locations?: { _id: string; name: string }[]
      pagination?: { totalCount: number }
      totals?: { total_hours: number; total_cost: number; record_count: number }
    }>(`/api/hours-aggregated?${params}`)
    if (res.success) {
      hoursData.value = res.data ?? []
      locations.value = res.locations ?? []
      paginationTotal.value = res.pagination?.totalCount ?? hoursData.value.length
      rangeTotals.value = {
        total_hours: res.totals?.total_hours ?? 0,
        total_cost: res.totals?.total_cost ?? 0,
        record_count: res.totals?.record_count ?? 0,
      }
    }
  } catch (e: unknown) {
    error.value = e instanceof Error ? e.message : 'Failed to fetch hours data'
    hoursData.value = []
  } finally {
    loading.value = false
  }
}

function onPageChange (p: number) {
  page.value = p
  void fetchHours(false)
}

function resetFilters () {
  const r = getLast30DaysRange()
  filters.startDate = r.startDate
  filters.endDate = r.endDate
  filters.locationId = 'all'
  filters.endpoint = 'time_registration_shifts'
  filters.sortBy = 'date'
  filters.sortOrder = 'desc'
  void fetchHours(true)
}

async function runConsistencyCheck () {
  consistencyLoading.value = true
  consistencyResult.value = null
  try {
    const params = new URLSearchParams()
    params.set('startDate', filters.startDate ?? defaultStart)
    params.set('endDate', filters.endDate ?? defaultEnd)
    params.set('endpoint', filters.endpoint ?? 'time_registration_shifts')
    const res = await $fetch<{
      success: boolean
      summary: { total_rows: number; ok_count: number; mismatch_count: number }
      mismatches: { date: string; location_name: string; location_id: string; row_total: number; raw_sum: number; raw_count: number; row_record_count: number; diff: number }[]
      possible_causes: string
    }>(`/api/hours-consistency-check?${params}`)
    if (res.success) consistencyResult.value = res
  } catch {
    consistencyResult.value = null
  } finally {
    consistencyLoading.value = false
  }
}

onMounted(() => {
  void fetchHours(true)
})
</script>

// app/(authenticated)/hours/page.tsx
/**
 * @registry-id: HoursPage
 * @created: 2026-01-22T00:00:00.000Z
 * @last-modified: 2026-01-22T00:00:00.000Z
 * @description: Hours overview page - shows hours per day per location with sort and filter
 * @last-fix: [2026-01-22] Initial implementation
 * 
 * @imports-from:
 *   - app/lib/hooks/useAuth.ts => useAuth for loading state
 *   - app/components/ui/data-table.tsx => DataTable component
 *   - app/components/ui/card.tsx => Card components
 *   - app/components/ui/select.tsx => Select for filters
 *   - app/components/ui/input.tsx => Input for date filters
 * 
 * @exports-to:
 *   ✓ app/components/DailyOpsSidebar.tsx => Navigation link
 */

'use client';

import { useAuth } from '@/lib/hooks/useAuth';
import { useEffect, useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { DataTable, DataTableColumn } from '@/components/ui/data-table';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';

interface HoursData {
  date: string;
  location_id: string;
  location_name: string;
  total_hours: number;
  total_cost: number;
  record_count: number;
}

interface Location {
  _id: string;
  name: string;
}

export default function HoursPage() {
  const { loading: authLoading } = useAuth();
  const [hoursData, setHoursData] = useState<HoursData[]>([]);
  const [locations, setLocations] = useState<Location[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  
  // Set default date range to last 30 days
  const today = new Date();
  const thirtyDaysAgo = new Date();
  thirtyDaysAgo.setDate(today.getDate() - 30);
  const defaultStartDate = thirtyDaysAgo.toISOString().split('T')[0];
  const defaultEndDate = today.toISOString().split('T')[0];
  
  const [filters, setFilters] = useState({
    startDate: defaultStartDate,
    endDate: defaultEndDate,
    locationId: 'all',
    endpoint: 'time_registration_shifts',
    sortBy: 'date',
    sortOrder: 'desc',
  });

  useEffect(() => {
    if (!authLoading) {
      fetchHoursData();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [authLoading, filters.startDate, filters.endDate, filters.locationId, filters.endpoint, filters.sortBy, filters.sortOrder]);

  async function fetchHoursData() {
    try {
      setLoading(true);
      setError(null);
      const params = new URLSearchParams();
      
      if (filters.startDate) params.append('startDate', filters.startDate);
      if (filters.endDate) params.append('endDate', filters.endDate);
      if (filters.locationId && filters.locationId !== 'all') params.append('locationId', filters.locationId);
      params.append('endpoint', filters.endpoint);
      params.append('sortBy', filters.sortBy);
      params.append('sortOrder', filters.sortOrder);

      const response = await fetch(`/api/hours?${params.toString()}`);
      if (response.ok) {
        const result = await response.json();
        if (result.success) {
          setHoursData(result.data || []);
          setLocations(result.locations || []);
        } else {
          setError(result.error || 'Failed to fetch hours data');
        }
      } else {
        const errorData = await response.json().catch(() => ({ error: 'Unknown error' }));
        setError(errorData.error || `HTTP ${response.status}: Failed to fetch hours data`);
      }
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Failed to fetch hours data';
      setError(errorMessage);
      console.error('Failed to fetch hours data:', error);
    } finally {
      setLoading(false);
    }
  }

  const handleFilterChange = (key: string, value: string) => {
    setFilters((prev) => ({ ...prev, [key]: value }));
  };

  const resetFilters = () => {
    setFilters({
      startDate: defaultStartDate,
      endDate: defaultEndDate,
      locationId: 'all',
      endpoint: 'time_registration_shifts',
      sortBy: 'date',
      sortOrder: 'desc',
    });
  };

  // Get column headers based on selected endpoint
  const getHoursHeader = () => {
    if (filters.endpoint === 'revenue_days') return 'Revenue';
    if (filters.endpoint === 'planning_shifts') return 'Planned Hours';
    return 'Total Hours';
  };

  const getCostHeader = () => {
    if (filters.endpoint === 'revenue_days') return 'Total Revenue';
    return 'Total Cost';
  };

  const columns: DataTableColumn<HoursData>[] = [
    {
      key: 'date',
      header: 'Date',
      render: (row) => {
        const date = new Date(row.date);
        return date.toLocaleDateString('en-US', {
          year: 'numeric',
          month: 'short',
          day: 'numeric',
        });
      },
    },
    {
      key: 'location_name',
      header: 'Location',
      render: (row) => row.location_name || 'Unknown',
    },
    {
      key: 'total_hours',
      header: getHoursHeader(),
      render: (row) => {
        if (filters.endpoint === 'revenue_days') {
          return `€${row.total_hours.toFixed(2)}`;
        }
        return row.total_hours.toFixed(2);
      },
    },
    {
      key: 'total_cost',
      header: getCostHeader(),
      render: (row) => `€${row.total_cost.toFixed(2)}`,
    },
    {
      key: 'record_count',
      header: 'Records',
      render: (row) => row.record_count,
    },
  ];

  if (authLoading) {
    return (
      <div className="p-8">
        <div className="text-center">Loading...</div>
      </div>
    );
  }

  return (
    <div className="p-8 space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Hours Overview</h1>
        <p className="text-muted-foreground">
          View hours worked per day per location
        </p>
      </div>

      {error && (
        <Card className="border-destructive">
          <CardContent className="pt-6">
            <div className="text-destructive">
              <strong>Error:</strong> {error}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Filters */}
      <Card>
        <CardHeader>
          <CardTitle>Filters</CardTitle>
          <CardDescription>Filter and sort hours data</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4 md:grid-cols-5">
            <div className="space-y-2">
              <Label htmlFor="endpoint">Endpoint</Label>
              <Select
                value={filters.endpoint}
                onValueChange={(value) => handleFilterChange('endpoint', value)}
              >
                <SelectTrigger id="endpoint">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="time_registration_shifts">Time Registration Shifts</SelectItem>
                  <SelectItem value="revenue_days">Revenue Days</SelectItem>
                  <SelectItem value="planning_shifts">Planning Shifts</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="startDate">Start Date</Label>
              <Input
                id="startDate"
                type="date"
                value={filters.startDate}
                onChange={(e) => handleFilterChange('startDate', e.target.value)}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="endDate">End Date</Label>
              <Input
                id="endDate"
                type="date"
                value={filters.endDate}
                onChange={(e) => handleFilterChange('endDate', e.target.value)}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="location">Location</Label>
              <Select
                value={filters.locationId}
                onValueChange={(value) => handleFilterChange('locationId', value)}
              >
                <SelectTrigger id="location">
                  <SelectValue placeholder="All locations" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All locations</SelectItem>
                  {locations.map((loc) => (
                    <SelectItem key={loc._id} value={loc._id}>
                      {loc.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="sortBy">Sort By</Label>
              <Select
                value={filters.sortBy}
                onValueChange={(value) => handleFilterChange('sortBy', value)}
              >
                <SelectTrigger id="sortBy">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="date">Date</SelectItem>
                  <SelectItem value="location">Location</SelectItem>
                  <SelectItem value="total_hours">Total Hours</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
          <div className="flex items-center gap-4 mt-4">
            <div className="space-y-2">
              <Label htmlFor="sortOrder">Sort Order</Label>
              <Select
                value={filters.sortOrder}
                onValueChange={(value) => handleFilterChange('sortOrder', value)}
              >
                <SelectTrigger id="sortOrder" className="w-[140px]">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="desc">Descending</SelectItem>
                  <SelectItem value="asc">Ascending</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <Button variant="outline" onClick={resetFilters} className="mt-6">
              Reset Filters
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Summary Stats */}
      {hoursData.length > 0 && (
        <div className="grid gap-4 md:grid-cols-3">
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Total Hours</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">
                {hoursData.reduce((sum, row) => sum + row.total_hours, 0).toFixed(2)}h
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Total Cost</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">
                €{hoursData.reduce((sum, row) => sum + row.total_cost, 0).toFixed(2)}
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Total Records</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">
                {hoursData.reduce((sum, row) => sum + row.record_count, 0)}
              </div>
            </CardContent>
          </Card>
        </div>
      )}

      {/* Hours Table */}
      <Card>
        <CardHeader>
          <CardTitle>Hours by Day and Location</CardTitle>
          <CardDescription>
            {loading ? 'Loading...' : `${hoursData.length} ${hoursData.length === 1 ? 'record' : 'records'} found`}
          </CardDescription>
        </CardHeader>
        <CardContent>
          {loading ? (
            <div className="text-center py-8">Loading hours data...</div>
          ) : hoursData.length === 0 ? (
            <div className="text-center py-8 space-y-4">
              <p className="text-muted-foreground">No hours data found for the selected date range.</p>
              <div className="text-sm text-muted-foreground space-y-2">
                <p>Hours data is synced from the Eitje API.</p>
                <p>To populate data:</p>
                <ul className="list-disc list-inside space-y-1 mt-2">
                  <li>Go to <strong>Settings → Eitje API</strong> to configure credentials</li>
                  <li>Use the <strong>/api/eitje/v2/sync</strong> endpoint to sync data</li>
                  <li>Or check if the automatic cron sync is running</li>
                </ul>
              </div>
            </div>
          ) : (
            <DataTable
              data={hoursData}
              columns={columns}
              searchable={false}
            />
          )}
        </CardContent>
      </Card>
    </div>
  );
}
