// app/daily-ops/hours/by-location/page.tsx
/**
 * @registry-id: HoursByLocationPage
 * @created: 2026-01-25T00:00:00.000Z
 * @last-modified: 2026-01-25T00:00:00.000Z
 * @description: Hours breakdown by location - shows total hours per location
 */

'use client';

import { useAuth } from '@/lib/hooks/useAuth';
import { useEffect, useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { DataTable, DataTableColumn } from '@/components/ui/data-table';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';

interface HoursByLocationData {
  location_id: string;
  location_name: string;
  location_names?: string[]; // Array of up to 3 location names from unified collection
  total_hours: number;
  total_cost: number;
  record_count: number;
  worker_count: number;
}

export default function HoursByLocationPage() {
  const { loading: authLoading } = useAuth();
  const [hoursData, setHoursData] = useState<HoursByLocationData[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  
  const today = new Date();
  const thirtyDaysAgo = new Date();
  thirtyDaysAgo.setDate(today.getDate() - 30);
  const defaultStartDate = thirtyDaysAgo.toISOString().split('T')[0];
  const defaultEndDate = today.toISOString().split('T')[0];
  
  const [filters, setFilters] = useState({
    startDate: defaultStartDate,
    endDate: defaultEndDate,
    endpoint: 'time_registration_shifts',
    sortBy: 'total_hours',
    sortOrder: 'desc',
  });

  useEffect(() => {
    if (!authLoading) {
      fetchHoursData();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [authLoading, filters.startDate, filters.endDate, filters.endpoint, filters.sortBy, filters.sortOrder]);

  async function fetchHoursData() {
    try {
      setLoading(true);
      setError(null);
      const params = new URLSearchParams();
      
      if (filters.startDate) params.append('startDate', filters.startDate);
      if (filters.endDate) params.append('endDate', filters.endDate);
      params.append('endpoint', filters.endpoint);
      params.append('groupBy', 'location');
      params.append('sortBy', filters.sortBy);
      params.append('sortOrder', filters.sortOrder);

      const response = await fetch(`/api/hours?${params.toString()}`);
      if (response.ok) {
        const result = await response.json();
        if (result.success) {
          setHoursData(result.data || []);
        } else {
          setError(result.error || 'Failed to fetch hours data');
        }
      } else {
        const errorData = await response.json().catch(() => ({ error: 'Unknown error' }));
        setError(errorData.error || `HTTP ${response.status}: Failed to fetch hours data`);
      }
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Failed to fetch hours data';
      setError(errorMessage);
    } finally {
      setLoading(false);
    }
  }

  const handleFilterChange = (key: string, value: string) => {
    setFilters((prev) => ({ ...prev, [key]: value }));
  };

  const resetFilters = () => {
    setFilters({
      startDate: defaultStartDate,
      endDate: defaultEndDate,
      endpoint: 'time_registration_shifts',
      sortBy: 'total_hours',
      sortOrder: 'desc',
    });
  };

  const columns: DataTableColumn<HoursByLocationData>[] = [
    {
      key: 'location_name',
      header: 'Location',
      render: (row) => {
        // Show up to 3 location names from unified collection
        const names = row.location_names && row.location_names.length > 0
          ? row.location_names
          : row.location_name
            ? [row.location_name]
            : ['Unknown'];
        
        return (
          <div className="space-y-1">
            {names.slice(0, 3).map((name, idx) => (
              <div key={idx} className="text-sm">
                {name}
              </div>
            ))}
          </div>
        );
      },
    },
    {
      key: 'total_hours',
      header: 'Total Hours',
      render: (row) => row.total_hours.toFixed(2),
    },
    {
      key: 'total_cost',
      header: 'Total Cost',
      render: (row) => `€${row.total_cost.toFixed(2)}`,
    },
    {
      key: 'worker_count',
      header: 'Workers',
      render: (row) => row.worker_count || 0,
    },
    {
      key: 'record_count',
      header: 'Records',
      render: (row) => row.record_count,
    },
  ];

  if (authLoading) {
    return (
      <div className="p-8">
        <div className="text-center">Loading...</div>
      </div>
    );
  }

  return (
    <div className="p-8 space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Hours by Location</h1>
        <p className="text-muted-foreground">
          View total hours worked per location
        </p>
      </div>


      {error && (
        <Card className="border-destructive">
          <CardContent className="pt-6">
            <div className="text-destructive">
              <strong>Error:</strong> {error}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Filters */}
      <Card>
        <CardHeader>
          <CardTitle>Filters</CardTitle>
          <CardDescription>Filter and sort hours data</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4 md:grid-cols-4">
            <div className="space-y-2">
              <Label htmlFor="endpoint">Endpoint</Label>
              <Select
                value={filters.endpoint}
                onValueChange={(value) => handleFilterChange('endpoint', value)}
              >
                <SelectTrigger id="endpoint">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="time_registration_shifts">Time Registration Shifts</SelectItem>
                  <SelectItem value="revenue_days">Revenue Days</SelectItem>
                  <SelectItem value="planning_shifts">Planning Shifts</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="startDate">Start Date</Label>
              <Input
                id="startDate"
                type="date"
                value={filters.startDate}
                onChange={(e) => handleFilterChange('startDate', e.target.value)}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="endDate">End Date</Label>
              <Input
                id="endDate"
                type="date"
                value={filters.endDate}
                onChange={(e) => handleFilterChange('endDate', e.target.value)}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="sortBy">Sort By</Label>
              <Select
                value={filters.sortBy}
                onValueChange={(value) => handleFilterChange('sortBy', value)}
              >
                <SelectTrigger id="sortBy">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="location_name">Location Name</SelectItem>
                  <SelectItem value="total_hours">Total Hours</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
          <div className="flex items-center gap-4 mt-4">
            <div className="space-y-2">
              <Label htmlFor="sortOrder">Sort Order</Label>
              <Select
                value={filters.sortOrder}
                onValueChange={(value) => handleFilterChange('sortOrder', value)}
              >
                <SelectTrigger id="sortOrder" className="w-[140px]">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="desc">Descending</SelectItem>
                  <SelectItem value="asc">Ascending</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <Button variant="outline" onClick={resetFilters} className="mt-6">
              Reset Filters
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Summary Stats */}
      {hoursData.length > 0 && (
        <div className="grid gap-4 md:grid-cols-3">
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Total Hours</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">
                {hoursData.reduce((sum, row) => sum + row.total_hours, 0).toFixed(2)}h
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Total Cost</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">
                €{hoursData.reduce((sum, row) => sum + row.total_cost, 0).toFixed(2)}
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Total Locations</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">
                {hoursData.length}
              </div>
            </CardContent>
          </Card>
        </div>
      )}

      {/* Hours Table */}
      <Card>
        <CardHeader>
          <CardTitle>Hours by Location</CardTitle>
          <CardDescription>
            {loading ? 'Loading...' : `${hoursData.length} ${hoursData.length === 1 ? 'location' : 'locations'} found`}
          </CardDescription>
        </CardHeader>
        <CardContent>
          {loading ? (
            <div className="text-center py-8">Loading hours data...</div>
          ) : (
            <>
              <DataTable
                data={hoursData}
                columns={columns}
                searchable={false}
              />
              {hoursData.length === 0 && !loading && (
                <div className="mt-4 text-center space-y-2">
                  <p className="text-sm text-muted-foreground">Hours data is synced from the Eitje API.</p>
                </div>
              )}
            </>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

// pages/daily-ops/hours/by-location.vue
<template>
  <div class="space-y-6">
    <div>
      <h1 class="text-3xl font-bold text-gray-900">Hours by Location</h1>
      <p class="text-gray-500">View total hours worked per location</p>
    </div>
    <UCard v-if="error"><p class="text-red-600"><strong>Error:</strong> {{ error }}</p></UCard>
    <UCard>
      <template #header><h2 class="font-semibold">Filters</h2></template>
      <div class="grid gap-4 md:grid-cols-4">
        <div class="space-y-2"><label class="text-sm font-medium">Endpoint</label><USelectMenu v-model="filters.endpoint" :items="endpointOptions" value-attribute="value" class="w-full" @update:model-value="() => fetchHours(true)" /></div>
        <div class="space-y-2"><label class="text-sm font-medium">Start Date</label><UInput v-model="filters.startDate" type="date" @update:model-value="() => fetchHours(true)" /></div>
        <div class="space-y-2"><label class="text-sm font-medium">End Date</label><UInput v-model="filters.endDate" type="date" @update:model-value="() => fetchHours(true)" /></div>
        <div class="space-y-2"><label class="text-sm font-medium">Sort By</label><USelectMenu v-model="filters.sortBy" :items="[{ label: 'Location Name', value: 'location_name' }, { label: 'Total Hours', value: 'total_hours' }]" value-attribute="value" class="w-full" @update:model-value="() => fetchHours(true)" /></div>
      </div>
      <div class="mt-4 flex gap-4">
        <div class="space-y-2"><label class="text-sm font-medium">Order</label><USelectMenu v-model="filters.sortOrder" :items="[{ label: 'Descending', value: 'desc' }, { label: 'Ascending', value: 'asc' }]" value-attribute="value" class="w-36" @update:model-value="() => fetchHours(true)" /></div>
        <UButton variant="outline" class="mt-6" @click="resetFilters">Reset</UButton>
      </div>
    </UCard>
    <div v-if="paginationTotal > 0" class="grid gap-4 md:grid-cols-3">
      <UCard><template #header><span class="text-sm font-medium">Total Hours</span></template><p class="text-2xl font-bold">{{ totalHours.toFixed(2) }}h</p></UCard>
      <UCard><template #header><span class="text-sm font-medium">Total Cost</span></template><p class="text-2xl font-bold">€{{ totalCost.toFixed(2) }}</p></UCard>
      <UCard><template #header><span class="text-sm font-medium">Locations (range)</span></template><p class="text-2xl font-bold">{{ paginationTotal }}</p></UCard>
    </div>
    <UCard>
      <template #header><h2 class="font-semibold">Hours by Location</h2><p class="text-sm text-gray-500">{{ loading ? 'Loading...' : `${paginationTotal} total · ${hoursData.length} on this page` }}</p></template>
      <div v-if="loading" class="py-8 text-center text-gray-500">Loading...</div>
      <div v-else class="overflow-x-auto">
        <table class="w-full text-left text-sm">
          <thead><tr class="border-b"><th class="pb-2 pr-4 font-medium">Location</th><th class="pb-2 pr-4 font-medium">Total Hours</th><th class="pb-2 pr-4 font-medium">Total Cost</th><th class="pb-2 pr-4 font-medium">Workers</th><th class="pb-2 font-medium">Records</th></tr></thead>
          <tbody>
            <tr v-for="(row, i) in hoursData" :key="i" class="border-b last:border-0">
              <td class="py-2 pr-4">{{ row.location_name ?? 'Unknown' }}</td>
              <td class="py-2 pr-4">{{ Number(row.total_hours ?? 0).toFixed(2) }}</td>
              <td class="py-2 pr-4">€{{ Number(row.total_cost ?? 0).toFixed(2) }}</td>
              <td class="py-2 pr-4">{{ row.worker_count ?? 0 }}</td>
              <td class="py-2">{{ row.record_count ?? 0 }}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div v-if="paginationTotal > pageSize" class="mt-6 flex justify-center">
        <UPagination :page="page" :total="paginationTotal" :items-per-page="pageSize" @update:page="onPageChange" />
      </div>
      <p v-if="hoursData.length === 0 && !loading" class="mt-4 text-center text-sm text-gray-500">Hours data is synced from the Eitje API.</p>
    </UCard>
  </div>
</template>

<script setup lang="ts">
/**
 * @registry-id: dailyOpsHoursByLocation
 * @last-modified: 2026-07-02T00:00:00.000Z
 * @description: Hours by location
 * @last-fix: [2026-07-02] ADR-013 read-cache metadata
 * @adr-ref: ADR-013
 * @data-source: direct-db
 * @read-cache-json: none
 * @imports-data-from: GET /api/hours/*
 */
const endpointOptions = [{ label: 'Time Registration Shifts', value: 'time_registration_shifts' }, { label: 'Revenue Days', value: 'revenue_days' }, { label: 'Planning Shifts', value: 'planning_shifts' }]
const { startDate: defaultStart, endDate: defaultEnd } = getLast30DaysRange()
const filters = reactive({ startDate: defaultStart, endDate: defaultEnd, endpoint: 'time_registration_shifts', sortBy: 'total_hours', sortOrder: 'desc' })
const hoursData = ref<Record<string, unknown>[]>([]), loading = ref(true), error = ref<string | null>(null)
const page = ref(1), pageSize = 50, paginationTotal = ref(0)
const rangeTotals = ref({ total_hours: 0, total_cost: 0, record_count: 0 })
const totalHours = computed(() => rangeTotals.value.total_hours)
const totalCost = computed(() => rangeTotals.value.total_cost)
async function fetchHours (resetPage = false) {
  if (resetPage) page.value = 1
  loading.value = true; error.value = null
  try {
    const params = new URLSearchParams()
    if (filters.startDate) params.set('startDate', filters.startDate); if (filters.endDate) params.set('endDate', filters.endDate)
    params.set('endpoint', filters.endpoint); params.set('groupBy', 'location'); params.set('sortBy', filters.sortBy); params.set('sortOrder', filters.sortOrder)
    params.set('page', String(page.value)); params.set('pageSize', String(pageSize))
    const res = await $fetch<{ success: boolean; data?: Record<string, unknown>[]; pagination?: { totalCount: number }; totals?: { total_hours: number; total_cost: number; record_count: number } }>(`/api/hours-aggregated?${params}`)
    if (res.success) {
      hoursData.value = res.data ?? []
      paginationTotal.value = res.pagination?.totalCount ?? hoursData.value.length
      rangeTotals.value = {
        total_hours: res.totals?.total_hours ?? 0,
        total_cost: res.totals?.total_cost ?? 0,
        record_count: res.totals?.record_count ?? 0,
      }
    } else hoursData.value = []
  } catch (e: unknown) { error.value = e instanceof Error ? e.message : 'Failed to fetch'; hoursData.value = [] }
  finally { loading.value = false }
}
function onPageChange (p: number) { page.value = p; void fetchHours(false) }
function resetFilters () { const r = getLast30DaysRange(); filters.startDate = r.startDate; filters.endDate = r.endDate; filters.endpoint = 'time_registration_shifts'; filters.sortBy = 'total_hours'; filters.sortOrder = 'desc'; void fetchHours(true) }
onMounted(() => { void fetchHours(true) })
</script>
