// pages/daily-ops/sales/by-day.vue
<template>
  <div class="space-y-6">
    <div>
      <h1 class="text-3xl font-bold text-gray-900">Sales by Day</h1>
      <p class="text-gray-500">View total sales revenue and quantity per day across all locations</p>
    </div>

    <UCard v-if="error" class="border-red-200">
      <p class="text-red-600"><strong>Error:</strong> {{ error }}</p>
    </UCard>

    <UCard>
      <template #header>
        <h2 class="font-semibold">Filters</h2>
        <p class="text-sm text-gray-500">Filter and sort sales by day</p>
      </template>
      <div class="grid gap-4 md:grid-cols-4">
        <div class="space-y-2">
          <label class="text-sm font-medium">Start Date</label>
          <UInput v-model="filters.startDate" type="date" @update:model-value="fetchSales" />
        </div>
        <div class="space-y-2">
          <label class="text-sm font-medium">End Date</label>
          <UInput v-model="filters.endDate" type="date" @update:model-value="fetchSales" />
        </div>
        <div class="space-y-2">
          <label class="text-sm font-medium">Sort By</label>
          <USelectMenu
            v-model="filters.sortBy"
            :items="sortByOptions"
            value-attribute="value"
            class="w-full"
            @update:model-value="fetchSales"
          />
        </div>
        <div class="space-y-2">
          <label class="text-sm font-medium">Order</label>
          <USelectMenu
            v-model="filters.sortOrder"
            :items="[{ label: 'Descending', value: 'desc' }, { label: 'Ascending', value: 'asc' }]"
            value-attribute="value"
            class="w-36"
            @update:model-value="fetchSales"
          />
        </div>
      </div>
      <div class="mt-4">
        <UButton variant="outline" @click="resetFilters">Reset Filters</UButton>
      </div>
    </UCard>

    <div v-if="salesData.length > 0" class="grid gap-4 md:grid-cols-3">
      <UCard>
        <template #header>
          <span class="text-sm font-medium">Total Revenue</span>
        </template>
        <p class="text-2xl font-bold">€{{ totalRevenue.toFixed(2) }}</p>
      </UCard>
      <UCard>
        <template #header>
          <span class="text-sm font-medium">Total Quantity</span>
        </template>
        <p class="text-2xl font-bold">{{ totalQuantity.toFixed(2) }}</p>
      </UCard>
      <UCard>
        <template #header>
          <span class="text-sm font-medium">Total Records</span>
        </template>
        <p class="text-2xl font-bold">{{ totalRecords }}</p>
      </UCard>
    </div>

    <UCard>
      <template #header>
        <h2 class="font-semibold">Sales by Day</h2>
        <p class="text-sm text-gray-500">
          {{ loading ? 'Loading...' : `${salesData.length} day(s) found` }}
        </p>
      </template>
      <div v-if="loading" class="py-8 text-center text-gray-500">Loading sales data...</div>
      <template v-else>
        <div class="overflow-x-auto">
          <table class="w-full text-left text-sm">
            <thead>
              <tr class="border-b">
                <th class="pb-2 pr-4 font-medium">Date</th>
                <th class="pb-2 pr-4 font-medium">Revenue</th>
                <th class="pb-2 pr-4 font-medium">Quantity</th>
                <th class="pb-2 pr-4 font-medium">Locations</th>
                <th class="pb-2 pr-4 font-medium">Records</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="(row, i) in salesData" :key="i" class="border-b transition-colors hover:bg-gray-50">
                <td class="py-2 pr-4">{{ formatDate(row.date) }}</td>
                <td class="py-2 pr-4">€{{ row.total_revenue != null ? Number(row.total_revenue).toFixed(2) : '0.00' }}</td>
                <td class="py-2 pr-4">{{ row.total_quantity != null ? Number(row.total_quantity).toFixed(2) : '0.00' }}</td>
                <td class="py-2 pr-4">{{ row.location_count ?? 0 }}</td>
                <td class="py-2 pr-4">{{ row.record_count ?? 0 }}</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p v-if="salesData.length === 0 && !loading" class="mt-4 text-center text-sm text-gray-500">
          Sales data is synced from the Bork API. Configure Settings → Bork API and run sync to populate.
        </p>
      </template>
    </UCard>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref, computed, onMounted } from 'vue'

const sortByOptions = [
  { label: 'Date', value: 'date' },
  { label: 'Revenue', value: 'total_revenue' },
  { label: 'Quantity', value: 'total_quantity' },
]

const today = new Date()
const defaultStart = '2025-01-01'
const defaultEnd = today.toISOString().split('T')[0]

const filters = reactive({
  startDate: defaultStart,
  endDate: defaultEnd,
  sortBy: 'date',
  sortOrder: 'desc',
})

const salesData = ref<Record<string, unknown>[]>([])
const loading = ref(false)
const error = ref<string | null>(null)

const totalRevenue = computed(() => {
  return salesData.value.reduce((sum: number, row: Record<string, unknown>) => sum + Number(row.total_revenue ?? 0), 0)
})

const totalQuantity = computed(() => {
  return salesData.value.reduce((sum: number, row: Record<string, unknown>) => sum + Number(row.total_quantity ?? 0), 0)
})

const totalRecords = computed(() => {
  return salesData.value.reduce((sum: number, row: Record<string, unknown>) => sum + (Number(row.record_count ?? 0)), 0)
})

const fetchSales = async () => {
  loading.value = true
  error.value = null
  try {
    const params = new URLSearchParams({
      startDate: filters.startDate,
      endDate: filters.endDate,
      locationId: 'all',
      groupBy: 'date',
      sortBy: filters.sortBy,
      sortOrder: filters.sortOrder,
    })
    const response = await $fetch<{ success: boolean; data?: Record<string, unknown>[]; locations?: Record<string, unknown>[]; summary?: Record<string, unknown> }>(`/api/sales-aggregated?${params}`)
    if (response.success) {
      salesData.value = response.data ?? []
    } else {
      error.value = 'Failed to load sales data'
    }
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Error loading sales data'
  } finally {
    loading.value = false
  }
}

const resetFilters = () => {
  filters.startDate = defaultStart
  filters.endDate = defaultEnd
  filters.sortBy = 'date'
  filters.sortOrder = 'desc'
  fetchSales()
}

const formatDate = (dateStr: string | undefined) => {
  if (!dateStr) return '-'
  try {
    return new Date(dateStr).toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })
  } catch {
    return dateStr
  }
}

onMounted(() => {
  fetchSales()
})
</script>

// app/daily-ops/hours/by-day/page.tsx
/**
 * @registry-id: HoursByDayPage
 * @created: 2026-01-25T00:00:00.000Z
 * @last-modified: 2026-01-25T00:00:00.000Z
 * @description: Hours breakdown by day - shows total hours per day across all locations
 */

'use client';

import { useAuth } from '@/lib/hooks/useAuth';
import { useEffect, useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { DataTable, DataTableColumn } from '@/components/ui/data-table';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';

interface HoursByDayData {
  date: string;
  total_hours: number;
  total_cost: number;
  record_count: number;
  location_count: number;
}

export default function HoursByDayPage() {
  const { loading: authLoading } = useAuth();
  const [hoursData, setHoursData] = useState<HoursByDayData[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  
  const today = new Date();
  const thirtyDaysAgo = new Date();
  thirtyDaysAgo.setDate(today.getDate() - 30);
  const defaultStartDate = thirtyDaysAgo.toISOString().split('T')[0];
  const defaultEndDate = today.toISOString().split('T')[0];
  
  const [filters, setFilters] = useState({
    startDate: defaultStartDate,
    endDate: defaultEndDate,
    endpoint: 'time_registration_shifts',
    sortBy: 'date',
    sortOrder: 'desc',
  });

  useEffect(() => {
    if (!authLoading) {
      fetchHoursData();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [authLoading, filters.startDate, filters.endDate, filters.endpoint, filters.sortBy, filters.sortOrder]);

  async function fetchHoursData() {
    try {
      setLoading(true);
      setError(null);
      const params = new URLSearchParams();
      
      if (filters.startDate) params.append('startDate', filters.startDate);
      if (filters.endDate) params.append('endDate', filters.endDate);
      params.append('endpoint', filters.endpoint);
      params.append('groupBy', 'day');
      params.append('sortBy', filters.sortBy);
      params.append('sortOrder', filters.sortOrder);

      const response = await fetch(`/api/hours-aggregated?${params.toString()}`);
      if (response.ok) {
        const result = await response.json();
        if (result.success) {
          setHoursData(result.data || []);
        } else {
          setError(result.error || 'Failed to fetch hours data');
        }
      } else {
        const errorData = await response.json().catch(() => ({ error: 'Unknown error' }));
        setError(errorData.error || `HTTP ${response.status}: Failed to fetch hours data`);
      }
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Failed to fetch hours data';
      setError(errorMessage);
    } finally {
      setLoading(false);
    }
  }

  const handleFilterChange = (key: string, value: string) => {
    setFilters((prev) => ({ ...prev, [key]: value }));
  };

  const resetFilters = () => {
    setFilters({
      startDate: defaultStartDate,
      endDate: defaultEndDate,
      endpoint: 'time_registration_shifts',
      sortBy: 'date',
      sortOrder: 'desc',
    });
  };

  const columns: DataTableColumn<HoursByDayData>[] = [
    {
      key: 'date',
      header: 'Date',
      render: (row) => {
        const date = new Date(row.date);
        return date.toLocaleDateString('en-US', {
          year: 'numeric',
          month: 'short',
          day: 'numeric',
        });
      },
    },
    {
      key: 'total_hours',
      header: 'Total Hours',
      render: (row) => row.total_hours.toFixed(2),
    },
    {
      key: 'total_cost',
      header: 'Total Cost',
      render: (row) => `€${row.total_cost.toFixed(2)}`,
    },
    {
      key: 'location_count',
      header: 'Locations',
      render: (row) => row.location_count || 0,
    },
    {
      key: 'record_count',
      header: 'Records',
      render: (row) => row.record_count,
    },
  ];

  if (authLoading) {
    return (
      <div className="p-8">
        <div className="text-center">Loading...</div>
      </div>
    );
  }

  return (
    <div className="p-8 space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Hours by Day</h1>
        <p className="text-muted-foreground">
          View total hours worked per day across all locations
        </p>
      </div>


      {error && (
        <Card className="border-destructive">
          <CardContent className="pt-6">
            <div className="text-destructive">
              <strong>Error:</strong> {error}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Filters */}
      <Card>
        <CardHeader>
          <CardTitle>Filters</CardTitle>
          <CardDescription>Filter and sort hours data</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4 md:grid-cols-4">
            <div className="space-y-2">
              <Label htmlFor="endpoint">Endpoint</Label>
              <Select
                value={filters.endpoint}
                onValueChange={(value) => handleFilterChange('endpoint', value)}
              >
                <SelectTrigger id="endpoint">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="time_registration_shifts">Time Registration Shifts</SelectItem>
                  <SelectItem value="revenue_days">Revenue Days</SelectItem>
                  <SelectItem value="planning_shifts">Planning Shifts</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="startDate">Start Date</Label>
              <Input
                id="startDate"
                type="date"
                value={filters.startDate}
                onChange={(e) => handleFilterChange('startDate', e.target.value)}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="endDate">End Date</Label>
              <Input
                id="endDate"
                type="date"
                value={filters.endDate}
                onChange={(e) => handleFilterChange('endDate', e.target.value)}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="sortBy">Sort By</Label>
              <Select
                value={filters.sortBy}
                onValueChange={(value) => handleFilterChange('sortBy', value)}
              >
                <SelectTrigger id="sortBy">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="date">Date</SelectItem>
                  <SelectItem value="total_hours">Total Hours</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
          <div className="flex items-center gap-4 mt-4">
            <div className="space-y-2">
              <Label htmlFor="sortOrder">Sort Order</Label>
              <Select
                value={filters.sortOrder}
                onValueChange={(value) => handleFilterChange('sortOrder', value)}
              >
                <SelectTrigger id="sortOrder" className="w-[140px]">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="desc">Descending</SelectItem>
                  <SelectItem value="asc">Ascending</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <Button variant="outline" onClick={resetFilters} className="mt-6">
              Reset Filters
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Summary Stats */}
      {hoursData.length > 0 && (
        <div className="grid gap-4 md:grid-cols-3">
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Total Hours</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">
                {hoursData.reduce((sum, row) => sum + row.total_hours, 0).toFixed(2)}h
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Total Cost</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">
                €{hoursData.reduce((sum, row) => sum + row.total_cost, 0).toFixed(2)}
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Total Records</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">
                {hoursData.reduce((sum, row) => sum + row.record_count, 0)}
              </div>
            </CardContent>
          </Card>
        </div>
      )}

      {/* Hours Table */}
      <Card>
        <CardHeader>
          <CardTitle>Hours by Day</CardTitle>
          <CardDescription>
            {loading ? 'Loading...' : `${hoursData.length} ${hoursData.length === 1 ? 'day' : 'days'} found`}
          </CardDescription>
        </CardHeader>
        <CardContent>
          {loading ? (
            <div className="text-center py-8">Loading hours data...</div>
          ) : (
            <>
              <DataTable
                data={hoursData}
                columns={columns}
                searchable={false}
              />
              {hoursData.length === 0 && !loading && (
                <div className="mt-4 text-center space-y-2">
                  <p className="text-sm text-muted-foreground">Hours data is synced from the Eitje API.</p>
                </div>
              )}
            </>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
